### ISSUE TITLE
'Edit this page' link broken

### ISSUE THREAD

**Issue by a-s-russo** [annasmyk/JD_Quarto_Book#41]
Clicking on 'Edit this page' (seemingly regardless of the page) leads to an error on GitHub:

![image](https://github.com/annasmyk/JD_Quarto_Book/assets/110582146/8a8447b3-18ea-4317-a262-ac26ea74deca)

**Comment by TanguyBarthelemy** [comment]
It's corrected! Thank you for reporting this
